name: chest_flutter
description: Utilities for working with Chest and Flutter.
version: 0.1.2
repository: https://github.com/chestdb/chest_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.4.2
  chest: ^0.1.1
  flutter:
    sdk: flutter
  flutter_tapers: ^0.1.1
  path_provider: ^2.0.0
